#!/bin/bash
gcc -I bigint/build/include -L bigint/build/lib -g -Wall -std=c99 -pedantic -o njvm njvm.c -lbigint
for filename in prog/*.asm; do
    ./nja "${filename}" "${filename}.bin" &
done
wait  # Warte, bis alle 'nja'-Prozesse abgeschlossen sind

for filename in prog/*.bin; do
    echo "${filename}"
    ./njvm "${filename}"  # Entferne die zusätzliche Klammer
done

for filename in prog/*.bin; do
    rm "${filename}"
done
